name: alignnet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - clearml
  - clearml-agent
  - hydra-core
  - IPython
  - matplotlib
  - numpy
  - pandas
  - pre-commit
  - poetry
  - pytorch
  - pytorch-cuda=11.8
  - conda-forge::pytorch-lightning
  - scipy
  - torchvision
  - torchaudio
  - pip
  - pip:
    - pylance
    - sox
    - soundfile
    - tensorboard
