name: alignnet-paper
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - clearml=1.16.1
  - clearml-agent
  - hydra-core=1.3.2
  - IPython
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pre-commit
  - poetry
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - conda-forge::pytorch-lightning=2.2.2
  - scipy
  - torchvision
  - torchaudio=2.3.0
  - pip
  - pip:
    - pandas=2.2.2
    - pylance
    - sox
    - soundfile
    - tensorboard=2.16.2
