[tool.poetry]
name = "alignnet"
version = "0.1.0"
description = ""
authors = ["Jaden Pieper <jpieper@ntia.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
