app_name: AlignNet

header: == Training ${hydra.help.app_name} ==

footer: |-
    Powered by Hydra (https://hyrda.cc)
    Use --hydra-help to view Hydra specific help.

template: |-
  ${hydra.help.header}

  This is ${hydra.help.app_name}!
  You can choose a db driver by appending
  == Configuration groups ==
  Compose your configuration from those groups (db=mysql)

  $APP_CONFIG_GROUPS

  == Config ==
  This is the config generated for this run.
  You can override everything, for example:
  python my_app.py db.user=foo db.pass=bar
  -------
  $CONFIG
  -------
  
  ${hydra.help.footer}